version: "3"

services:
  assembly:
    container_name: why_assembly
    image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1
    command: sh -c "cd /data && ./sbt assembly"
    volumes:
      - "./:/data"
    stdin_open: true
    tty: true

  server:
    container_name: why_server
    image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1
    command: sh -c "cd /data/server/target/scala-0.21 && java -jar server-assembly-0.1.0-SNAPSHOT.jar"
    expose:
      - "4242"
    ports:
      - "4242:4242"
    volumes:
      - "./:/data"
    networks:
      - why-net

  client-ascii:
    container_name: why_clinet_ascii
    image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1
    command: sh -c "cd /data/client-ascii/target/scala-0.21 && java -jar client-assembly-0.1.0-SNAPSHOT.jar why_server 4242"
    volumes:
      - "./:/data"
    networks:
      - why-net
    stdin_open: true
    tty: true

networks:
  why-net:
    driver: bridge
